[package]
name = "nom-bencode"
version = "0.1.0"
edition = "2021"

exclude = ["./test-assets/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
thiserror = "1.0.31"

[dev-dependencies]
assert_matches = "1.5.0"
